"""Canonical manual screenshot manifest; screenshots are captured by students."""


# --- Manual F12 evidence manifest (DOCX-only reporting) ---
LEGACY_SCREENSHOT_NAMES = ()
F12_SCREENSHOTS = ({'filename': '01_victim_login_session.png',
  'objective': 'Thiết lập session victim',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/login',
  'account': 'victim / Victim123!',
  'data': 'username=victim; password che',
  'action': 'Đăng nhập',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload/Headers; Application Cookies',
  'request': 'POST /login',
  'field': 'Form Data; Set-Cookie',
  'required': 'Redirect thành công; `lab04_session` hiện diện với HttpOnly/SameSite/Path',
  'expected': 'Victim đã đăng nhập',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Đăng nhập victim và tạo session local',
  'report_section': 'F12 / Session',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '02_email_before.png',
  'objective': 'Ghi email trước thao tác',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/profile',
  'account': 'victim',
  'data': 'Không',
  'action': 'Mở profile',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /profile',
  'field': 'Response/Preview',
  'required': 'Email `victim_old@lab.local` và session local',
  'expected': 'Baseline trước CSRF',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Email victim trước request CSRF',
  'report_section': 'F12 / State before',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '03_legitimate_email_request.png',
  'objective': 'Chứng minh request đổi email hợp lệ ở vulnerable route',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/vulnerable/change-email',
  'account': 'victim',
  'data': 'email=demo_changed@lab.local',
  'action': 'Submit từ Victim UI',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload/Headers',
  'request': 'POST /vulnerable/change-email',
  'field': 'General, Request Headers, Form Data',
  'required': 'Method POST, route, form email và Cookie đã che',
  'expected': 'Email đổi thành công ở flow hợp lệ',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request đổi email hợp lệ',
  'report_section': 'F12 / Legitimate request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '04_vulnerable_no_token_payload.png',
  'objective': 'Chứng minh vulnerable request không có CSRF token',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/vulnerable/change-email',
  'account': 'victim',
  'data': 'email=demo_changed@lab.local',
  'action': 'Chọn POST',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /vulnerable/change-email',
  'field': 'Form Data',
  'required': 'Chỉ có email; không có `csrf_token`',
  'expected': 'Route phụ thuộc session cookie',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Vulnerable Form Data thiếu CSRF token',
  'report_section': 'F12 / Vulnerable / Token',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '05_attacker_form_dom.png',
  'objective': 'Chứng minh form attacker local',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:9004/attack/vulnerable-email',
  'account': 'victim đang đăng nhập ở victim origin',
  'data': 'email=demo_changed@lab.local',
  'action': 'Mở trang, chưa submit',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Elements',
  'request': 'N/A',
  'field': 'Form action/method/hidden input',
  'required': 'action trỏ `http://127.0.0.1:5004/vulnerable/change-email`, method POST, email cố định',
  'expected': 'Form cross-origin có thể tạo request',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'DOM form của Demo Page local',
  'report_section': 'F12 / Attacker form',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '06_attacker_origin_request.png',
  'objective': 'Chứng minh request phát sinh từ Demo Page',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:9004/attack/vulnerable-email',
  'account': 'victim',
  'data': 'email=demo_changed@lab.local',
  'action': 'Bấm gửi và xác nhận',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Payload',
  'request': 'POST http://127.0.0.1:5004/vulnerable/change-email',
  'field': 'Origin, Referer, Sec-Fetch-Site, Cookie, Form Data',
  'required': 'Origin/Referer là :9004; Sec-Fetch-Site nếu browser có; Cookie tự gửi nếu policy cho phép',
  'expected': 'Request cross-origin tới victim',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request CSRF từ Demo Page local',
  'report_section': 'F12 / Vulnerable / Cross-origin request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '07_vulnerable_response_success.png',
  'objective': 'Chứng minh vulnerable response cho phép',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/vulnerable/change-email',
  'account': 'victim',
  'data': 'email demo_changed',
  'action': 'Chọn request attacker',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'POST /vulnerable/change-email',
  'field': 'Status và Response',
  'required': 'Status thành công/redirect và thông báo email đã đổi',
  'expected': 'State bị thay đổi do thiếu token',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response vulnerable đổi email thành công',
  'report_section': 'F12 / Vulnerable / Response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '08_email_after_csrf.png',
  'objective': 'Ghi email sau CSRF',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/profile',
  'account': 'victim',
  'data': 'Không',
  'action': 'Mở profile sau attack',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'GET /profile',
  'field': 'Response/UI',
  'required': 'Email `demo_changed@lab.local`',
  'expected': 'So sánh trước/sau rõ ràng',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Email victim sau request CSRF',
  'report_section': 'F12 / State after',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '09_secure_form_token.png',
  'objective': 'Chứng minh form secure có token',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/secure/change-email',
  'account': 'victim',
  'data': 'email=secure_changed@lab.local',
  'action': 'Mở form, chưa submit',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Elements',
  'request': 'GET /secure/change-email',
  'field': 'hidden input',
  'required': 'Input hidden `csrf_token` có giá trị; che phần lớn token',
  'expected': 'Token gắn với session',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Form secure chứa CSRF token',
  'report_section': 'F12 / Secure / Form',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '10_secure_valid_request.png',
  'objective': 'Chứng minh request secure có token hợp lệ',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/secure/change-email',
  'account': 'victim',
  'data': 'email=secure_changed@lab.local; csrf_token che',
  'action': 'Submit từ Victim UI',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload/Headers',
  'request': 'POST /secure/change-email',
  'field': 'Form Data, Origin, Referer, Cookie',
  'required': 'Token hiện diện (che), Origin/Referer victim origin, cookie che',
  'expected': 'Request secure hợp lệ',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request secure có token hợp lệ',
  'report_section': 'F12 / Secure / Valid request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '11_secure_valid_response.png',
  'objective': 'Chứng minh token hợp lệ cho phép update',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/secure/change-email',
  'account': 'victim',
  'data': 'email=secure_changed@lab.local',
  'action': 'Chọn POST secure',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'POST /secure/change-email',
  'field': 'Status và Response',
  'required': 'Thành công; email mới; token rotate theo trace nếu hiển thị',
  'expected': 'Secure flow hoạt động bình thường',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure với token hợp lệ',
  'report_section': 'F12 / Secure / Valid response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '12_secure_missing_token_request.png',
  'objective': 'Chứng minh request giả mạo thiếu token',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:9004/attack/secure-email',
  'account': 'victim',
  'data': 'email=demo_changed@lab.local; không token',
  'action': 'Bấm gửi và xác nhận',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload/Headers',
  'request': 'POST /secure/change-email',
  'field': 'Form Data, Origin, Referer, Cookie',
  'required': 'Không có csrf_token; origin :9004; cookie nếu policy cho phép',
  'expected': 'Server nhận request không đủ bằng chứng',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request secure giả mạo thiếu token',
  'report_section': 'F12 / Secure / Missing token',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '13_secure_missing_token_403.png',
  'objective': 'Chứng minh secure từ chối thiếu token',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/secure/change-email',
  'account': 'victim',
  'data': 'Thiếu token',
  'action': 'Chọn request ảnh 12',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'POST /secure/change-email',
  'field': 'Status và Response',
  'required': 'HTTP 403 và thông báo token missing/denied; email không đổi',
  'expected': 'Bản vá chặn request',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response 403 khi thiếu CSRF token',
  'report_section': 'F12 / Secure / Denied',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '14_secure_bad_token_payload.png',
  'objective': 'Chứng minh token sai bị gửi',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:9004/attack/bad-token',
  'account': 'victim',
  'data': 'csrf_token=giá trị giả cố định của trang',
  'action': 'Bấm gửi và xác nhận',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /secure/change-email',
  'field': 'Form Data',
  'required': 'Token giả hiện diện nhưng không khớp; che nếu dài',
  'expected': 'Server kiểm tra equality/timing-safe',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request secure với token sai',
  'report_section': 'F12 / Secure / Bad token',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '15_secure_bad_token_403.png',
  'objective': 'Chứng minh secure từ chối token sai',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/secure/change-email',
  'account': 'victim',
  'data': 'Token sai',
  'action': 'Chọn request ảnh 14',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response',
  'request': 'POST /secure/change-email',
  'field': 'Status/Response',
  'required': 'HTTP 403; reason token mismatch; state không đổi',
  'expected': 'Token validation hiệu quả',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response 403 khi CSRF token sai',
  'report_section': 'F12 / Secure / Bad token response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '16_cookie_samesite_application.png',
  'objective': 'Chứng minh SameSite/HttpOnly/Secure',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/profile',
  'account': 'victim',
  'data': 'Không',
  'action': 'Mở cookie victim origin',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application/Storage > Cookies',
  'request': 'GET /profile',
  'field': 'Name, Domain, Path, HttpOnly, Secure, SameSite',
  'required': '`lab04_session`, Path=/, HttpOnly=true, SameSite theo config, Secure phản ánh HTTP local; che Value',
  'expected': 'Cookie flags là defense-in-depth',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Cookie SameSite của Victim Application',
  'report_section': 'F12 / Cookie',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '17_set_cookie_response_header.png',
  'objective': 'Chứng minh Set-Cookie từ response login',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5004/login',
  'account': 'victim',
  'data': 'Đăng nhập lại nếu cần',
  'action': 'Chọn POST login',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'POST /login',
  'field': 'Response Headers',
  'required': 'Set-Cookie có HttpOnly, Path, SameSite; Secure chỉ khi config bật',
  'expected': 'Header khớp Application',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Set-Cookie của session victim',
  'report_section': 'F12 / Cookie / Response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '18_origin_validation_denied.png',
  'objective': 'Chứng minh Origin/Referer validation nếu request tới bước này',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://localhost:9004/attack/secure-email',
  'account': 'victim',
  'data': 'Request cross-site thiếu token',
  'action': 'Submit từ localhost:9004',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'POST /secure/change-email',
  'field': 'Origin, Referer, Response',
  'required': 'Origin/Referer localhost:9004 và decision denied theo source/trace',
  'expected': 'Exact origin là lớp bổ sung',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Origin validation từ chối cross-origin',
  'report_section': 'F12 / Origin validation',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '19_preserve_log_redirect_chain.png',
  'objective': 'Chứng minh redirect không làm mất request',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:9004/attack/vulnerable-email',
  'account': 'victim',
  'data': 'email demo_changed',
  'action': 'Bật Preserve log trước submit',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network',
  'request': 'POST và request tiếp theo',
  'field': 'Status/Initiator',
  'required': 'Chuỗi request giữ lại, Initiator là form document',
  'expected': 'Nguồn request được truy vết',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Preserve log giữ chuỗi CSRF request',
  'report_section': 'F12 / Network workflow',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '20_cookie_auto_sent_header.png',
  'objective': 'Chứng minh browser tự gửi cookie',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:9004/attack/vulnerable-email',
  'account': 'victim',
  'data': 'Không biết cookie value',
  'action': 'Submit form',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'POST /vulnerable/change-email',
  'field': 'Request Headers > Cookie',
  'required': 'Cookie header có tên session nhưng Value phải che; attacker form không chứa cookie field',
  'expected': 'Browser tự gắn credential theo policy',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Cookie tự gửi trong request CSRF',
  'report_section': 'F12 / Cookie flow',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False})
OPTIONAL_SCREENSHOT_NAMES = frozenset(name for name in LEGACY_SCREENSHOT_NAMES if 'pytest' in name or 'coverage' in name)
ALL_SCREENSHOTS = tuple({'filename': name, 'optional': name in OPTIONAL_SCREENSHOT_NAMES} for name in LEGACY_SCREENSHOT_NAMES) + F12_SCREENSHOTS
