"""Danh sách bằng chứng ảnh duy nhất của Lab02."""

SCREENSHOTS = [
    {"filename":"01_normal_input.png","title":"Input bình thường xử lý thành công","purpose":"Chứng minh HTTP và tiến trình native xử lý tên ngắn thành công.","initial":"Đã build binary trong WSL/Docker và chạy app local.","location":"http://127.0.0.1:5002/vulnerable","data":"Le Minh, profile vulnerable_debug.","button":"Bấm Submit/Gửi.","panel":"Request Inspector và Native Process Inspector (ghép cùng UI).","required":"POST /submit, input ngắn, exit code/stdout thực tế và không có overflow.","expected":"Chương trình xử lý thành công mà không crash.","caption":"Input bình thường đi qua HTTP và tiến trình native thành công."},
    {"filename":"02_overflow_http_crash.png","title":"Input dài làm bản vulnerable dừng","purpose":"Chứng minh input dài qua HTTP làm tiến trình vulnerable dừng/crash có kiểm soát.","initial":"Chọn profile vulnerable_asan hoặc vulnerable_debug; không dùng secure.","location":"http://127.0.0.1:5002/vulnerable","data":"64 ký tự A.","button":"Bấm Submit/Gửi.","panel":"Request Inspector và Native Process/Final Verdict.","required":"POST length=64 và exit code/signal/crash thực tế của tiến trình.","expected":"Tiến trình vulnerable bị ASan dừng hoặc crash; app web vẫn hoạt động.","caption":"Input 64 byte qua HTTP kích hoạt lỗi trong backend native vulnerable."},
    {"filename":"03_asan_log.png","title":"AddressSanitizer định vị ghi vượt buffer","purpose":"Ghi nhận loại lỗi, hàm và dòng nguồn từ stderr thật.","initial":"Vừa chạy ảnh 02 bằng vulnerable_asan.","location":"ASan Inspector hoặc evidence/asan từ lần chạy thật.","data":"Trace 64 ký tự A.","button":"Mở ASan Inspector/chi tiết stack trace.","panel":"ASan Inspector.","required":"stack-buffer-overflow, WRITE, process_name/strcpy, file và dòng liên quan.","expected":"ASan báo ghi vượt name[32] trong mã vulnerable.","caption":"ASan phát hiện stack-buffer-overflow tại thao tác strcpy."},
    {"filename":"04_gdb_backtrace.png","title":"GDB tại vị trí lỗi","purpose":"Chứng minh stack frame/backtrace từ binary debug local.","initial":"Mở Ubuntu/WSL tại Lab02, đã make all.","location":"gdb -q -x gdb/inspect_overflow.gdb","data":"Input do script GDB local cung cấp.","button":"Chạy lệnh và tiếp tục theo script.","panel":"Terminal GDB.","required":"Điểm dừng/signal, frame process_name, name[32] hoặc backtrace.","expected":"GDB định vị lỗi trong stack frame của process_name; không sửa thanh ghi.","caption":"GDB xác nhận vị trí lỗi và backtrace của phiên overflow local."},
    {"filename":"05_length_thresholds.png","title":"Mốc capacity, ASan và crash","purpose":"Xác định nhiều độ dài thay vì suy diễn một mốc duy nhất.","initial":"Đã build các binary trong WSL/Docker.","location":"python scripts/test_lengths.py (hoặc bảng kết quả tích hợp nếu script hiện có).","data":"Các độ dài quanh 31, 32, 40, 64 byte.","button":"Chạy lệnh/test và mở bảng kết quả.","panel":"Terminal hoặc Length Test table.","required":"Capacity 31 byte, mốc ASan đầu tiên và mốc crash đầu tiên từ kết quả thật.","expected":"Phân biệt ranh giới buffer, phát hiện ASan và crash thực tế.","caption":"Kiểm tra nhiều độ dài xác định capacity, mốc ASan và mốc crash."},
    {"filename":"06_length_fix.png","title":"Bản vá kiểm tra độ dài","purpose":"Chứng minh input quá dài bị từ chối trước khi copy.","initial":"Chọn secure_length.","location":"http://127.0.0.1:5002/secure/length","data":"64 ký tự A.","button":"Bấm Submit/Gửi.","panel":"Native/Code Inspector và Final Verdict.","required":"strnlen/so sánh giới hạn, từ chối trước copy và exit/status thực tế.","expected":"Không ghi vào buffer khi input vượt 31 byte.","caption":"Bản vá kiểm tra độ dài từ chối input trước thao tác copy."},
    {"filename":"07_snprintf_fix.png","title":"Bản vá snprintf xử lý truncation","purpose":"Chứng minh snprintf có giới hạn và kiểm tra giá trị trả về.","initial":"Chọn secure_snprintf.","location":"http://127.0.0.1:5002/secure/snprintf","data":"64 ký tự A.","button":"Bấm Submit/Gửi.","panel":"Native/Code Inspector và Final Verdict.","required":"snprintf, sizeof(name), return value và từ chối truncation.","expected":"Input dài bị từ chối, không được coi là xử lý thành công.","caption":"Bản vá snprintf phát hiện và từ chối kết quả bị cắt ngắn."},
    {"filename":"08_hardening.png","title":"Canary, PIE, RELRO và NX","purpose":"Chứng minh thuộc tính hardening từ binary thật.","initial":"Đã make all, gồm secure_hardened.","location":"http://127.0.0.1:5002/hardening","data":"Không nhập dữ liệu.","button":"Mở/refresh Hardening Inspector.","panel":"Hardening Inspector.","required":"Canary, PIE, RELRO, NX của profile so sánh; nguồn lệnh kiểm tra binary.","expected":"Các cơ chế bật/tắt đọc từ binary thật và được mô tả là lớp bổ sung.","caption":"Canary, PIE, RELRO và NX tăng chiều sâu bảo vệ cho binary."},
    {"filename":"09_tests_reports.png","title":"Pytest và report artifacts","purpose":"Chứng minh kiểm thử thật và báo cáo được sinh.","initial":"Chạy trong WSL/Docker nếu test cần binary Linux.","location":"python -m pytest -q; python scripts/generate_report.py; ls -lh report/","data":"Ba lệnh trên.","button":"Chạy lần lượt.","panel":"Terminal.","required":"Tổng kết pytest thực tế, tên DOCX/PDF và kích thước khác 0.","expected":"Chỉ ghi đạt khi pytest exit 0; report artifacts tồn tại.","caption":"Kết quả pytest thực tế và report artifacts của Lab02."},
]

REQUIRED_FILENAMES = tuple(item["filename"] for item in SCREENSHOTS)
