"""Nguồn duy nhất mô tả tám ảnh bằng chứng bắt buộc của Lab05."""

SCREENSHOTS = (
    {"name": "01_normal_login_search.png", "title": "Đăng nhập và tìm kiếm bình thường", "url": "http://127.0.0.1:5005/vulnerable/login và /vulnerable/search?keyword=USB", "action": "Đăng nhập bằng tài khoản demo rồi tìm USB; ghép hai trạng thái nếu vẫn đọc được.", "panel": "Network > request tương ứng", "must_show": "localhost, input bình thường, request và kết quả đúng", "expected": "Đăng nhập thành công; tìm kiếm chỉ trả kết quả phù hợp.", "caption": "Luồng đăng nhập và tìm kiếm bình thường trên ứng dụng local."},
    {"name": "02_quote_error.png", "title": "Dấu nháy đơn làm lộ lỗi ở bản vulnerable", "url": "http://127.0.0.1:5005/vulnerable/login", "action": "Bấm kịch bản Dấu nháy đơn và gửi form.", "panel": "Error Inspector hoặc Network Response", "must_show": "input có dấu nháy, lỗi truy vấn đã xử lý và trace/query liên quan", "expected": "Bản vulnerable có hành vi lỗi nhưng không lộ traceback hay đường dẫn.", "caption": "Dấu nháy đơn phá cấu trúc câu SQL nối chuỗi ở bản vulnerable."},
    {"name": "03_auth_bypass.png", "title": "Authentication bypass trong lab local", "url": "http://127.0.0.1:5005/vulnerable/login", "action": "Chọn kịch bản authentication logic cố định, gửi form và mở Query/Authentication Inspector.", "panel": "Network + Query Construction hoặc Authentication Decision", "must_show": "request, SQL đã biến đổi và trạng thái đăng nhập khi không biết mật khẩu", "expected": "Điều kiện WHERE bị thay đổi và phiên demo được tạo.", "caption": "Nối chuỗi SQL làm thay đổi logic xác thực trong lab local."},
    {"name": "04_search_expanded.png", "title": "SQL Injection mở rộng kết quả tìm kiếm", "url": "http://127.0.0.1:5005/vulnerable/search", "action": "Chọn kịch bản mở rộng kết quả cố định rồi tìm kiếm.", "panel": "Query Construction + Result Set", "must_show": "keyword, SQL biến đổi và nhiều sản phẩm ngoài từ khóa bình thường", "expected": "Tập kết quả mở rộng nhưng chỉ trong bảng products giả lập.", "caption": "Điều kiện tìm kiếm bị thay đổi làm mở rộng tập kết quả."},
    {"name": "05_secure_login.png", "title": "Secure login dùng parameter binding", "url": "http://127.0.0.1:5005/secure/login", "action": "Gửi lại đúng chuỗi kiểm thử của ảnh 03.", "panel": "Query Construction + Authentication Decision", "must_show": "SQL có placeholder, tham số tách riêng và đăng nhập bị từ chối", "expected": "Chuỗi được coi là dữ liệu, cấu trúc SQL không đổi.", "caption": "Parameterized query từ chối cùng chuỗi kiểm thử đăng nhập."},
    {"name": "06_secure_search.png", "title": "Secure search bind tham số", "url": "http://127.0.0.1:5005/secure/search", "action": "Gửi lại đúng keyword của ảnh 04.", "panel": "Query Construction + Result Set", "must_show": "LIKE ? hoặc placeholder, tham số riêng và tập kết quả không mở rộng", "expected": "Không có sản phẩm ngoài ý muốn.", "caption": "Bind tham số giữ nguyên cấu trúc SQL và không mở rộng kết quả."},
    {"name": "07_password_error_code.png", "title": "Password hashing, lỗi an toàn và bản vá", "url": "http://127.0.0.1:5005/comparison và /security-controls", "action": "Mở so sánh code; ghép phần PBKDF2, generic error và vulnerable/secure query.", "panel": "Code Comparison hoặc Security Controls", "must_show": "đoạn nối chuỗi, placeholder, PBKDF2 và lỗi chung", "expected": "Root cause và bản vá đọc được trong một ảnh.", "caption": "Bản vá kết hợp parameter binding, PBKDF2 và thông báo lỗi an toàn."},
    {"name": "08_test_report.png", "title": "Kiểm thử, coverage và report artifacts", "url": "Terminal tại thư mục Lab05", "action": "Chạy pytest, coverage và generator; hiển thị thư mục report trong cùng cửa sổ.", "panel": "Terminal", "must_show": "dòng tổng kết pytest thật, coverage thật và tên DOCX/PDF đã sinh", "expected": "Chỉ ghi nhận đúng kết quả lệnh vừa chạy.", "caption": "Kết quả kiểm thử, coverage và báo cáo được sinh từ dữ liệu thật."},
)

EXPECTED_FILES = tuple(item["name"] for item in SCREENSHOTS)
