"""Canonical manual screenshot manifest; screenshots are captured by students."""


# --- Manual F12 evidence manifest (DOCX-only reporting) ---
LEGACY_SCREENSHOT_NAMES = ('01_home_overview.png',
 '02_normal_input_before_submit.png',
 '03_normal_http_request.png',
 '04_normal_native_process.png',
 '05_normal_memory_visualizer.png',
 '06_overflow_32_input.png',
 '07_overflow_32_memory_boundary.png',
 '08_overflow_64_request.png',
 '09_overflow_64_strcpy_step.png',
 '10_overflow_64_memory_visualizer.png',
 '11_asan_detected.png',
 '12_asan_stack_trace.png',
 '13_native_crash_result.png',
 '14_final_vulnerable_verdict.png',
 '15_length_test_table.png',
 '16_gdb_breakpoint.png',
 '17_gdb_local_buffer.png',
 '18_gdb_overflow_stop.png',
 '19_secure_length_reject.png',
 '20_secure_length_timeline.png',
 '21_secure_snprintf_reject.png',
 '22_code_comparison.png',
 '23_hardening_comparison.png',
 '24_stack_canary_explanation.png',
 '25_asan_vs_hardening.png',
 '26_presentation_mode.png',
 '27_pytest_passed.png',
 '28_report_files.png')
F12_SCREENSHOTS = ({'filename': '29_normal_network_payload.png',
  'objective': 'Chứng minh request bình thường từ browser tới backend',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/vulnerable',
  'account': 'N/A',
  'data': 'name=Le Minh; mode=vulnerable_asan',
  'action': 'Bấm Gửi dữ liệu',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /submit',
  'field': 'Form Data',
  'required': 'name `Le Minh`, mode `vulnerable_asan`, Content-Type form',
  'expected': 'Request bình thường được backend nhận',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Payload HTTP bình thường tới chương trình C',
  'report_section': 'F12 / Normal / Request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '30_normal_network_response.png',
  'objective': 'Chứng minh response thành công',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/vulnerable',
  'account': 'N/A',
  'data': 'Le Minh',
  'action': 'Chọn POST vừa gửi',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'POST /submit',
  'field': 'Response và status',
  'required': 'HTTP thành công; trace/HTML có native exit code 0 hoặc trạng thái thực',
  'expected': 'UI hiển thị kết quả xử lý bình thường',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response bình thường từ backend native',
  'report_section': 'F12 / Normal / Response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '31_long_input_network_payload.png',
  'objective': 'Chứng minh request input dài',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/vulnerable',
  'account': 'N/A',
  'data': 'A lặp 64; mode=vulnerable_asan',
  'action': 'Submit input dài',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /submit',
  'field': 'Form Data',
  'required': 'Chuỗi A dài và mode; độ dài 64 thể hiện trong UI/trace',
  'expected': 'Backend nhận input dài có kiểm soát',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Payload 64 byte gửi tới bản vulnerable',
  'report_section': 'F12 / Long input / Request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '32_long_input_network_response.png',
  'objective': 'Ghi response lỗi hoặc trạng thái backend thực',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/vulnerable',
  'account': 'N/A',
  'data': 'A lặp 64',
  'action': 'Chọn request 64 byte',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Timing',
  'request': 'POST /submit',
  'field': 'Status, Response, Timing',
  'required': 'Response lỗi/ASan/exit/signal/connection state đúng quan sát; không khẳng định crash nếu không thấy',
  'expected': 'Kết quả phản ánh tiến trình C thực',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response của input dài ở bản vulnerable',
  'report_section': 'F12 / Long input / Response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '33_browser_to_c_trace.png',
  'objective': 'Chứng minh luồng browser → Flask → subprocess → C',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/vulnerable',
  'account': 'N/A',
  'data': 'Trace 64 byte đã có',
  'action': 'Mở Request Inspector và Native Inspector cạnh Network',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers; UI Trace',
  'request': 'POST /submit',
  'field': 'Request URL, mode, trace id và native result',
  'required': 'Cùng trace nối request browser với binary/process/exit',
  'expected': 'Luồng web-to-native được đối chiếu',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'UI trace đối chiếu request tới chương trình C',
  'report_section': 'F12 / Trace',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '34_secure_length_network_response.png',
  'objective': 'Chứng minh bản vá length từ chối input dài',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/secure/length',
  'account': 'N/A',
  'data': 'A lặp 64; mode=secure_length',
  'action': 'Submit',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload và Response',
  'request': 'POST /secure/length/submit',
  'field': 'Form Data; Response',
  'required': 'Input length 64; response từ chối/giới hạn trước copy',
  'expected': 'Không overflow ở bản length check',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure_length từ chối input dài',
  'report_section': 'F12 / Secure length',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '35_secure_snprintf_network_response.png',
  'objective': 'Chứng minh bản snprintf xử lý giới hạn',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/secure/snprintf',
  'account': 'N/A',
  'data': 'A lặp 64; mode=secure_snprintf',
  'action': 'Submit',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload và Response',
  'request': 'POST /secure/snprintf/submit',
  'field': 'Form Data; Response',
  'required': 'Input dài; response báo reject/truncation theo source',
  'expected': 'Bản vá không ghi vượt buffer',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure_snprintf kiểm soát input dài',
  'report_section': 'F12 / Secure snprintf',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '36_patched_request_comparison.png',
  'objective': 'So sánh cùng input giữa vulnerable và secure',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/comparison',
  'account': 'N/A',
  'data': 'A lặp 64',
  'action': 'Giữ Preserve log; gửi lần lượt vulnerable và secure',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network',
  'request': 'Ba POST tương ứng',
  'field': 'Headers/Payload/Response',
  'required': 'Cùng độ dài input; route và response khác nhau',
  'expected': 'Bản vá từ chối hoặc giới hạn có chủ đích',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'So sánh HTTP vulnerable và secure',
  'report_section': 'F12 / Comparison',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '37_backend_unavailable_timing.png',
  'objective': 'Ghi trạng thái nếu backend native không khả dụng',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/vulnerable',
  'account': 'N/A',
  'data': 'Input 64 byte',
  'action': 'Chỉ dùng khi request thực sự lỗi/reset',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Timing/Response',
  'request': 'POST /submit',
  'field': 'Timing và status',
  'required': 'Failed/connection reset/5xx hoặc thông báo binary unavailable đúng thực tế',
  'expected': 'Không diễn giải lỗi giả thành crash',
  'troubleshooting': 'Nếu request trả bình thường, không tạo ảnh giả; dùng ảnh response thực và ghi trạng thái quan sát được.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Trạng thái Network khi backend không trả bình thường',
  'report_section': 'F12 / Error handling',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '38_secure_payload_limit.png',
  'objective': 'Chứng minh giới hạn input ở response secure',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5002/secure/length',
  'account': 'N/A',
  'data': 'A lặp 256 là tối đa cấu hình; không vượt giới hạn lab',
  'action': 'Submit và chọn request',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload/Response',
  'request': 'POST /secure/length/submit',
  'field': 'Form Data và Response',
  'required': 'Độ dài input; thông báo giới hạn/từ chối; không shellcode',
  'expected': 'Server áp chính sách độ dài',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Giới hạn input của bản vá',
  'report_section': 'F12 / Secure / Limit',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False})
OPTIONAL_SCREENSHOT_NAMES = frozenset(name for name in LEGACY_SCREENSHOT_NAMES if 'pytest' in name or 'coverage' in name)
ALL_SCREENSHOTS = tuple({'filename': name, 'optional': name in OPTIONAL_SCREENSHOT_NAMES} for name in LEGACY_SCREENSHOT_NAMES) + F12_SCREENSHOTS
