SCREENSHOTS = [
    ("01_home_overview.png", "/", "Mở trang chủ", "Tên Lab01, ba loại XSS và liên kết vulnerable/secure"),
    ("02_reflected_input_step.png", "/vulnerable/search", "Nhập payload nhưng chưa gửi", "Ô input và payload"),
    ("03_reflected_request_step.png", "/vulnerable/search", "Gửi form, mở tab Request", "GET, route, query string, URL encoded"),
    ("04_reflected_server_step.png", "/vulnerable/search", "Chọn bước Flask Router/Validation", 'request.args["q"] và dữ liệu decoded'),
    ("05_reflected_template_step.png", "/vulnerable/search", "Chọn Template Engine", "Markup(q), dữ liệu chưa escape"),
    ("06_reflected_browser_parse_step.png", "/vulnerable/search", "Chọn Browser HTML Parser", "img element và onerror"),
    ("07_reflected_payload_executed.png", "/vulnerable/search", "Chạy payload rồi xem verdict", "Alert hoặc verdict payload_executed"),
    ("08_reflected_secure_encoding.png", "/secure/search", "Gửi cùng payload", "HTML escaped và text node"),
    ("09_reflected_comparison.png", "/secure/search", "Mở tab So sánh mã", "Markup(q) cạnh Jinja autoescape"),
    ("10_stored_post_request.png", "/vulnerable/post/1/comments", "POST bình luận payload, mở Request", "Form body đã che cookie"),
    ("11_stored_database_insert.png", "/vulnerable/post/1/comments", "Chọn SQLite INSERT", "Parameterized query và dữ liệu lưu"),
    ("12_stored_database_record.png", "/vulnerable/post/1/comments", "Mở Database Inspector", "Bản ghi payload thật trong SQLite"),
    ("13_stored_template_render.png", "/vulnerable/post/1/comments", "Reload, chọn Template Engine", "SELECT rồi render Markup"),
    ("14_stored_payload_reload.png", "/vulnerable/post/1/comments", "Reload và xem verdict", "Alert hoặc payload_executed"),
    ("15_stored_secure_escape.png", "/secure/post/1/comments", "Mở bản secure", "Dữ liệu DB không thực thi"),
    ("16_stored_secure_sanitize.png", "/secure/post/1/comments", "POST img + strong, mở Biến đổi", "Trước/sau Bleach sanitization"),
    ("17_stored_comparison.png", "/secure/post/1/comments", "Mở So sánh mã", "Markup cạnh bleach.clean"),
    ("18_dom_hash_source.png", "/vulnerable/dom-search", "Đặt fragment payload", "location.href và location.hash"),
    ("19_dom_javascript_read.png", "/vulnerable/dom-search", "Chọn Browser JavaScript", "Giá trị trước/sau decodeURIComponent"),
    ("20_dom_innerhtml_sink.png", "/vulnerable/dom-search", "Chọn bước DOM", "innerHTML và dữ liệu sink"),
    ("21_dom_element_created.png", "/vulnerable/dom-search", "Xem DOM Inspector", "img element và onerror trong DOM thật"),
    ("22_dom_payload_executed.png", "/vulnerable/dom-search", "Chạy fragment", "Alert hoặc verdict payload_executed"),
    ("23_dom_textcontent_fix.png", "/secure/dom-search", "Đặt cùng fragment", "textContent và text node"),
    ("24_dom_comparison.png", "/secure/dom-search", "Mở So sánh mã", "innerHTML cạnh textContent"),
    ("25_csp_headers.png", "/security-headers", "Mở bảng và trace CSP", "CSP cùng directive chính"),
    ("26_cookie_security.png", "/profile", "Mở bảng cookie", "HttpOnly, SameSite, Secure local/production"),
    ("27_presentation_mode.png", "/secure/search?q=demo", "Bật Presentation Mode", "Bước hiện tại và thanh tiến trình"),
    ("28_pytest_passed.png", "Terminal", "Chạy pytest -q", "Dòng tổng kết toàn bộ test đạt"),
]

# --- Manual F12 evidence manifest (DOCX-only reporting) ---
LEGACY_SCREENSHOT_NAMES = ('01_home_overview.png',
 '02_reflected_input_step.png',
 '03_reflected_request_step.png',
 '04_reflected_server_step.png',
 '05_reflected_template_step.png',
 '06_reflected_browser_parse_step.png',
 '07_reflected_payload_executed.png',
 '08_reflected_secure_encoding.png',
 '09_reflected_comparison.png',
 '10_stored_post_request.png',
 '11_stored_database_insert.png',
 '12_stored_database_record.png',
 '13_stored_template_render.png',
 '14_stored_payload_reload.png',
 '15_stored_secure_escape.png',
 '16_stored_secure_sanitize.png',
 '17_stored_comparison.png',
 '18_dom_hash_source.png',
 '19_dom_javascript_read.png',
 '20_dom_innerhtml_sink.png',
 '21_dom_element_created.png',
 '22_dom_payload_executed.png',
 '23_dom_textcontent_fix.png',
 '24_dom_comparison.png',
 '25_csp_headers.png',
 '26_cookie_security.png',
 '27_presentation_mode.png',
 '28_pytest_passed.png')
F12_SCREENSHOTS = ({'filename': '29_reflected_network_request.png',
  'objective': 'Chứng minh GET Reflected XSS thật',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/search',
  'account': 'Không đăng nhập',
  'data': '<img src=x onerror="alert(\'Reflected XSS\')">',
  'action': 'Nhập payload và bấm Tìm kiếm',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /vulnerable/search?q=...',
  'field': 'General và Query String Parameters',
  'required': 'Request URL local, method GET, status và q đã percent-encode',
  'expected': 'Request được gửi tới bản vulnerable',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Reflected XSS - request GET trong Network',
  'report_section': 'F12 / Reflected / Request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '30_reflected_query_parameters.png',
  'objective': 'Đối chiếu payload URL-encoded và giá trị decoded',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/search',
  'account': 'Không đăng nhập',
  'data': '<img src=x onerror="alert(\'Reflected XSS\')">',
  'action': 'Chọn lại request tìm kiếm',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload hoặc Headers',
  'request': 'GET /vulnerable/search?q=...',
  'field': 'Query String Parameters',
  'required': 'q hiển thị payload decoded; Request URL có `%3C`, `%3E` hoặc encoding tương đương',
  'expected': 'DevTools phân biệt URL encoding với nội dung q',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Query String Parameters của payload Reflected XSS',
  'report_section': 'F12 / Reflected / Payload',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '31_reflected_response_html.png',
  'objective': 'Chứng minh response phản chiếu payload vào HTML',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/search',
  'account': 'Không đăng nhập',
  'data': 'Payload Reflected an toàn của lab',
  'action': 'Mở Response của request',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response',
  'request': 'GET /vulnerable/search?q=...',
  'field': 'Response',
  'required': 'HTML vùng `Kết quả cho` chứa thẻ img/onerror chưa encode',
  'expected': 'Response vulnerable chứa sink HTML',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response HTML phản chiếu payload chưa encode',
  'report_section': 'F12 / Reflected / Response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '32_reflected_elements_node.png',
  'objective': 'Chứng minh browser tạo element/event handler',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/search',
  'account': 'Không đăng nhập',
  'data': 'Payload Reflected',
  'action': 'Đóng alert; Inspect vùng kết quả',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Elements',
  'request': 'N/A - dùng cùng lần GET',
  'field': 'DOM node và attributes',
  'required': 'Node `img` có thuộc tính `onerror` trong vùng kết quả',
  'expected': 'DOM tạo element từ response vulnerable',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Elements chứng minh img/onerror được tạo',
  'report_section': 'F12 / Reflected / DOM',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '33_stored_post_payload.png',
  'objective': 'Chứng minh POST lưu Stored XSS',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/post/1/comments',
  'account': 'Không đăng nhập',
  'data': 'author=Kiểm thử; body=<img src=x onerror="alert(\'Stored XSS\')"><strong>Xin chào</strong>',
  'action': 'Bấm Đăng bình luận',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /vulnerable/post/1/comments',
  'field': 'Form Data',
  'required': 'author và body đúng payload; cookie nếu có phải che',
  'expected': 'POST được xử lý rồi redirect/reload',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Stored XSS - Form Data của POST',
  'report_section': 'F12 / Stored / Request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '34_stored_reload_request.png',
  'objective': 'Chứng minh browser tải lại trang sau khi lưu',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/post/1/comments',
  'account': 'Không đăng nhập',
  'data': 'Payload đã lưu ở ảnh 33',
  'action': 'Bật Preserve log rồi submit/reload',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /vulnerable/post/1/comments sau POST',
  'field': 'General',
  'required': 'Chuỗi POST rồi GET/redirect cùng origin local',
  'expected': 'Trang được tải lại sau khi lưu',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Stored XSS - request reload sau POST',
  'report_section': 'F12 / Stored / Reload',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '35_stored_response_persisted.png',
  'objective': 'Chứng minh payload tiếp tục tồn tại sau reload',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/post/1/comments',
  'account': 'Không đăng nhập',
  'data': 'Payload Stored đã lưu',
  'action': 'Reload và chọn GET',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response; Elements',
  'request': 'GET /vulnerable/post/1/comments',
  'field': 'Response hoặc DOM node',
  'required': 'Payload/img/onerror xuất hiện lại từ dữ liệu SQLite',
  'expected': 'Stored payload tồn tại qua request mới',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response/Elements chứng minh Stored XSS tồn tại',
  'report_section': 'F12 / Stored / Persistence',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '36_dom_fragment_not_sent.png',
  'objective': 'Chứng minh location.hash không được gửi lên server',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/dom-search',
  'account': 'Không đăng nhập',
  'data': '#<img src=x onerror="alert(\'DOM XSS\')">',
  'action': 'Xóa Network; nhập payload; bấm Thay fragment không reload',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /vulnerable/dom-search nếu có; không có request mới khi chỉ đổi hash',
  'field': 'Request URL',
  'required': 'Request URL không chứa fragment; thay hash không phát sinh HTTP mới',
  'expected': 'Fragment chỉ ở client',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Network không gửi fragment DOM XSS',
  'report_section': 'F12 / DOM / Network',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '37_dom_elements_innerhtml.png',
  'objective': 'Chứng minh innerHTML tạo node',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/dom-search',
  'account': 'Không đăng nhập',
  'data': 'Payload DOM an toàn',
  'action': 'Inspect `#dom-result` sau khi đổi hash',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Elements',
  'request': 'Không có request chứa fragment',
  'field': 'DOM subtree',
  'required': '`section#dom-result` chứa `img` và `onerror`',
  'expected': 'innerHTML parse chuỗi thành HTML',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Elements chứng minh innerHTML tạo node',
  'report_section': 'F12 / DOM / Sink',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '38_dom_console_execution.png',
  'objective': 'Chứng minh JavaScript thực thi ở client',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/vulnerable/dom-search',
  'account': 'Không đăng nhập',
  'data': 'Payload DOM an toàn',
  'action': 'Quan sát alert hoặc verdict; Console chỉ để xem lỗi/trạng thái',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Console hoặc UI',
  'request': 'Không có request mới',
  'field': 'Console/UI',
  'required': 'Alert `DOM XSS` hoặc verdict `payload_executed`; không chạy lệnh đọc cookie',
  'expected': 'Payload thực thi cục bộ',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'UI/Console chứng minh DOM XSS thực thi',
  'report_section': 'F12 / DOM / Execution',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '39_secure_reflected_encoding_response.png',
  'objective': 'Chứng minh output encoding ở bản secure',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/secure/search',
  'account': 'Không đăng nhập',
  'data': 'Cùng payload Reflected',
  'action': 'Submit rồi mở Response',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response',
  'request': 'GET /secure/search?q=...',
  'field': 'Response',
  'required': 'Payload hiển thị dạng text/escaped, không tạo img/onerror',
  'expected': 'Bản secure không thực thi',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure dùng output encoding',
  'report_section': 'F12 / Secure / Encoding',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '40_secure_stored_sanitization.png',
  'objective': 'Chứng minh sanitization loại bỏ nội dung nguy hiểm',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/secure/post/1/comments',
  'account': 'Không đăng nhập',
  'data': 'Payload Stored có img/onerror và strong',
  'action': 'Submit rồi mở Response/Elements',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response; Elements',
  'request': 'POST rồi GET /secure/post/1/comments',
  'field': 'Response/DOM',
  'required': 'Không còn img/onerror; nội dung/strong cho phép vẫn an toàn',
  'expected': 'Bleach allowlist chặn handler',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Sanitization của Stored XSS secure',
  'report_section': 'F12 / Secure / Sanitization',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '41_secure_dom_textcontent.png',
  'objective': 'Chứng minh textContent tạo text node',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/secure/dom-search',
  'account': 'Không đăng nhập',
  'data': 'Cùng fragment DOM',
  'action': 'Đổi fragment; Inspect `#dom-result`',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Elements',
  'request': 'Không có request chứa fragment',
  'field': 'DOM subtree',
  'required': 'Chuỗi `<img...>` là text; không có element/event attribute',
  'expected': 'textContent không parse HTML',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Elements chứng minh textContent an toàn',
  'report_section': 'F12 / Secure / DOM',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '42_secure_csp_response_headers.png',
  'objective': 'Chứng minh CSP trong response headers',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/security-headers',
  'account': 'Không đăng nhập',
  'data': 'Không',
  'action': 'Reload trang',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /security-headers',
  'field': 'Response Headers',
  'required': 'Content-Security-Policy và X-Content-Type-Options/Referrer-Policy/X-Frame-Options',
  'expected': 'Header defense-in-depth có mặt',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response Headers có CSP',
  'report_section': 'F12 / Headers',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '43_cookie_flags_application.png',
  'objective': 'Chứng minh cookie flags local',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5000/profile',
  'account': 'Không đăng nhập',
  'data': 'Không',
  'action': 'Reload rồi mở cookie của origin local',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application/Storage > Cookies',
  'request': 'GET /profile',
  'field': 'Name, Domain, Path, HttpOnly, Secure, SameSite',
  'required': 'HttpOnly=true, SameSite=Lax, Secure phản ánh cấu hình local; che Value',
  'expected': 'Cookie flags khớp cấu hình Flask',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Application hiển thị cookie flags',
  'report_section': 'F12 / Cookies',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False})
OPTIONAL_SCREENSHOT_NAMES = frozenset(name for name in LEGACY_SCREENSHOT_NAMES if 'pytest' in name or 'coverage' in name)
ALL_SCREENSHOTS = tuple({'filename': name, 'optional': name in OPTIONAL_SCREENSHOT_NAMES} for name in LEGACY_SCREENSHOT_NAMES) + F12_SCREENSHOTS
