SCREENSHOTS = [
    ("01_home_overview.png", "/", "Mở trang chủ", "Tên Lab01, ba loại XSS và liên kết vulnerable/secure"),
    ("02_reflected_input_step.png", "/vulnerable/search", "Nhập payload nhưng chưa gửi", "Ô input và payload"),
    ("03_reflected_request_step.png", "/vulnerable/search", "Gửi form, mở tab Request", "GET, route, query string, URL encoded"),
    ("04_reflected_server_step.png", "/vulnerable/search", "Chọn bước Flask Router/Validation", 'request.args["q"] và dữ liệu decoded'),
    ("05_reflected_template_step.png", "/vulnerable/search", "Chọn Template Engine", "Markup(q), dữ liệu chưa escape"),
    ("06_reflected_browser_parse_step.png", "/vulnerable/search", "Chọn Browser HTML Parser", "img element và onerror"),
    ("07_reflected_payload_executed.png", "/vulnerable/search", "Chạy payload rồi xem verdict", "Alert hoặc verdict payload_executed"),
    ("08_reflected_secure_encoding.png", "/secure/search", "Gửi cùng payload", "HTML escaped và text node"),
    ("09_reflected_comparison.png", "/secure/search", "Mở tab So sánh mã", "Markup(q) cạnh Jinja autoescape"),
    ("10_stored_post_request.png", "/vulnerable/post/1/comments", "POST bình luận payload, mở Request", "Form body đã che cookie"),
    ("11_stored_database_insert.png", "/vulnerable/post/1/comments", "Chọn SQLite INSERT", "Parameterized query và dữ liệu lưu"),
    ("12_stored_database_record.png", "/vulnerable/post/1/comments", "Mở Database Inspector", "Bản ghi payload thật trong SQLite"),
    ("13_stored_template_render.png", "/vulnerable/post/1/comments", "Reload, chọn Template Engine", "SELECT rồi render Markup"),
    ("14_stored_payload_reload.png", "/vulnerable/post/1/comments", "Reload và xem verdict", "Alert hoặc payload_executed"),
    ("15_stored_secure_escape.png", "/secure/post/1/comments", "Mở bản secure", "Dữ liệu DB không thực thi"),
    ("16_stored_secure_sanitize.png", "/secure/post/1/comments", "POST img + strong, mở Biến đổi", "Trước/sau Bleach sanitization"),
    ("17_stored_comparison.png", "/secure/post/1/comments", "Mở So sánh mã", "Markup cạnh bleach.clean"),
    ("18_dom_hash_source.png", "/vulnerable/dom-search", "Đặt fragment payload", "location.href và location.hash"),
    ("19_dom_javascript_read.png", "/vulnerable/dom-search", "Chọn Browser JavaScript", "Giá trị trước/sau decodeURIComponent"),
    ("20_dom_innerhtml_sink.png", "/vulnerable/dom-search", "Chọn bước DOM", "innerHTML và dữ liệu sink"),
    ("21_dom_element_created.png", "/vulnerable/dom-search", "Xem DOM Inspector", "img element và onerror trong DOM thật"),
    ("22_dom_payload_executed.png", "/vulnerable/dom-search", "Chạy fragment", "Alert hoặc verdict payload_executed"),
    ("23_dom_textcontent_fix.png", "/secure/dom-search", "Đặt cùng fragment", "textContent và text node"),
    ("24_dom_comparison.png", "/secure/dom-search", "Mở So sánh mã", "innerHTML cạnh textContent"),
    ("25_csp_headers.png", "/security-headers", "Mở bảng và trace CSP", "CSP cùng directive chính"),
    ("26_cookie_security.png", "/profile", "Mở bảng cookie", "HttpOnly, SameSite, Secure local/production"),
    ("27_presentation_mode.png", "/secure/search?q=demo", "Bật Presentation Mode", "Bước hiện tại và thanh tiến trình"),
    ("28_pytest_passed.png", "Terminal", "Chạy pytest -q", "Dòng tổng kết toàn bộ test đạt"),
]
