"""Danh sách bằng chứng ảnh duy nhất của Lab01.

Checker, hướng dẫn và report generator cùng dùng thứ tự này.  Nội dung ảnh
được người học chụp thủ công; manifest không tự đánh giá nội dung.
"""

SCREENSHOTS = [
    {
        "filename": "01_reflected_vulnerable.png",
        "title": "Reflected XSS ở bản vulnerable",
        "purpose": "Chứng minh input/URL đi qua request và payload kiểm thử an toàn chạy.",
        "initial": "Mở bản vulnerable, xóa kết quả tìm kiếm cũ.",
        "location": "http://127.0.0.1:5000/vulnerable/search",
        "data": '<img src=x onerror="alert(\'XSS\')">',
        "button": "Bấm Tìm kiếm.",
        "panel": "DevTools Network > request search hoặc Request Inspector tích hợp.",
        "required": "Thanh địa chỉ localhost, query/input, GET request và alert/verdict payload_executed.",
        "expected": "Payload được phản chiếu không escape và chạy trong trình duyệt.",
        "caption": "Reflected XSS xảy ra khi dữ liệu q được đưa thẳng vào HTML.",
    },
    {
        "filename": "02_reflected_secure.png",
        "title": "Reflected XSS đã được encode",
        "purpose": "Chứng minh cùng payload được hiển thị như văn bản và không chạy.",
        "initial": "Đóng alert, mở bản secure.",
        "location": "http://127.0.0.1:5000/secure/search",
        "data": '<img src=x onerror="alert(\'XSS\')">',
        "button": "Bấm Tìm kiếm.",
        "panel": "Response Inspector hoặc DevTools Elements.",
        "required": "Chuỗi &lt;img...&gt; hoặc text node, không có element img nguy hiểm, verdict blocked.",
        "expected": "Jinja autoescape/output encoding làm payload không chạy.",
        "caption": "Output encoding biến payload Reflected XSS thành văn bản an toàn.",
    },
    {
        "filename": "03_stored_submit.png",
        "title": "Gửi và lưu Stored XSS",
        "purpose": "Chứng minh bình luận chứa payload được POST và lưu trong SQLite.",
        "initial": "Chạy python scripts/reset_database.py rồi mở trang bình luận vulnerable.",
        "location": "http://127.0.0.1:5000/vulnerable/post/1/comments",
        "data": 'Tác giả: SinhVien; nội dung: <img src=x onerror="alert(\'XSS\')">',
        "button": "Bấm Gửi bình luận.",
        "panel": "Request Inspector và Database Inspector tích hợp (ghép cùng UI nếu đọc được).",
        "required": "POST body đã che cookie và bản ghi comments chứa payload trong SQLite.",
        "expected": "Server lưu dữ liệu thật; việc dùng SQL tham số không tự ngăn XSS.",
        "caption": "Payload Stored XSS được gửi bằng POST và lưu trong cơ sở dữ liệu.",
    },
    {
        "filename": "04_stored_reload.png",
        "title": "Stored XSS chạy lại sau reload",
        "purpose": "Chứng minh payload lưu trữ ảnh hưởng lần xem sau.",
        "initial": "Giữ bản ghi của ảnh 03 và đóng alert.",
        "location": "http://127.0.0.1:5000/vulnerable/post/1/comments",
        "data": "Không nhập thêm dữ liệu.",
        "button": "Reload trang (hoặc mở lại bằng phiên local khác).",
        "panel": "Final Verdict/Timeline tích hợp.",
        "required": "Bình luận đã lưu và alert/verdict payload_executed sau reload.",
        "expected": "Payload chạy lại mỗi khi người dùng xem trang chứa bản ghi.",
        "caption": "Stored XSS tiếp tục chạy từ dữ liệu đã lưu sau khi tải lại trang.",
    },
    {
        "filename": "05_stored_secure.png",
        "title": "Stored XSS đã sanitize/escape",
        "purpose": "Chứng minh dữ liệu vẫn hiển thị nhưng script không chạy.",
        "initial": "Giữ dữ liệu DB của ảnh 03, mở bản secure.",
        "location": "http://127.0.0.1:5000/secure/post/1/comments",
        "data": "Không nhập thêm dữ liệu.",
        "button": "Reload trang.",
        "panel": "Biến đổi sanitization và DOM/Final Verdict.",
        "required": "Dữ liệu gốc, dữ liệu sau Bleach/escape và verdict không thực thi.",
        "expected": "Event handler nguy hiểm bị loại hoặc encode; nội dung an toàn vẫn hiển thị.",
        "caption": "Sanitization theo allowlist và escaping chặn Stored XSS.",
    },
    {
        "filename": "06_dom_vulnerable.png",
        "title": "DOM-based XSS ở innerHTML",
        "purpose": "Chứng minh location.hash đi tới innerHTML và tạo element nguy hiểm.",
        "initial": "Mở trang DOM vulnerable, xóa fragment cũ.",
        "location": "http://127.0.0.1:5000/vulnerable/dom-search#%3Cimg%20src%3Dx%20onerror%3Dalert('XSS')%3E",
        "data": "Fragment payload an toàn như trong URL.",
        "button": "Nhấn Enter hoặc kích hoạt hashchange.",
        "panel": "DOM Inspector/DevTools Elements và bước innerHTML.",
        "required": "location.hash, sink innerHTML, element img/onerror và alert/verdict executed.",
        "expected": "JavaScript phía client tạo DOM nguy hiểm mà fragment không gửi tới server.",
        "caption": "DOM-based XSS phát sinh khi location.hash được gán vào innerHTML.",
    },
    {
        "filename": "07_dom_secure.png",
        "title": "DOM-based XSS đã dùng textContent",
        "purpose": "Chứng minh cùng fragment chỉ tạo text node.",
        "initial": "Đóng alert và mở trang DOM secure.",
        "location": "http://127.0.0.1:5000/secure/dom-search#%3Cimg%20src%3Dx%20onerror%3Dalert('XSS')%3E",
        "data": "Cùng fragment của ảnh 06.",
        "button": "Nhấn Enter hoặc kích hoạt hashchange.",
        "panel": "DOM Inspector/DevTools Elements và bước textContent.",
        "required": "Source location.hash, sink textContent, text node, không có img/onerror thực thi.",
        "expected": "Payload hiển thị nguyên văn và không chạy.",
        "caption": "textContent loại bỏ khả năng diễn giải fragment thành HTML.",
    },
    {
        "filename": "08_code_fixes.png",
        "title": "Ba nguyên nhân và ba bản vá XSS",
        "purpose": "Đối chiếu ngắn root cause và fix của Reflected, Stored và DOM XSS.",
        "initial": "Đã tạo trace cho ba kịch bản secure/vulnerable.",
        "location": "Các tab So sánh mã trong ba trang secure; có thể ghép thành một ảnh.",
        "data": "Không nhập thêm dữ liệu.",
        "button": "Mở So sánh mã ở từng kịch bản.",
        "panel": "Code Comparison tích hợp.",
        "required": "Markup(q)/autoescape, Markup(row)/Bleach và innerHTML/textContent.",
        "expected": "Đọc rõ ba sink lỗi và ba thay đổi sửa lỗi.",
        "caption": "So sánh nguyên nhân và bản vá cho ba loại XSS.",
    },
    {
        "filename": "09_csp_cookie.png",
        "title": "CSP và thuộc tính cookie",
        "purpose": "Chứng minh các lớp phòng thủ bổ sung CSP và cookie flags.",
        "initial": "Mở profile local để tạo demo cookie.",
        "location": "http://127.0.0.1:5000/security-headers và /profile",
        "data": "Không nhập dữ liệu.",
        "button": "Reload hai trang nếu cần.",
        "panel": "DevTools Network > Response Headers và Application > Cookies (ghép khi chữ đọc được).",
        "required": "Content-Security-Policy; HttpOnly, SameSite, Path và trạng thái Secure local/production.",
        "expected": "Header/cookie flags hiện rõ; ghi nhận đây là defense in depth, không thay bản vá code.",
        "caption": "CSP và cookie flags giảm tác động nhưng không thay thế sửa sink XSS.",
    },
    {
        "filename": "10_tests_reports.png",
        "title": "Pytest và report artifacts",
        "purpose": "Chứng minh kết quả kiểm thử thật và hai báo cáo được sinh.",
        "initial": "Đóng ứng dụng khác đang giữ file report.",
        "location": "Terminal tại thư mục Lab01.",
        "data": "python -m pytest -q; python scripts/generate_report.py; Get-ChildItem report",
        "button": "Chạy lần lượt ba lệnh.",
        "panel": "Terminal; không cần DevTools.",
        "required": "Dòng tổng kết pytest thực tế, tên DOCX/PDF và kích thước khác 0.",
        "expected": "Chỉ ghi đạt nếu pytest trả exit code 0; report artifacts tồn tại.",
        "caption": "Kết quả pytest thực tế và các report artifacts của Lab01.",
    },
]

REQUIRED_FILENAMES = tuple(item["filename"] for item in SCREENSHOTS)
