"""Nguồn duy nhất mô tả chín ảnh bằng chứng bắt buộc của Lab06."""

SCREENSHOTS = (
    {"name": "01_cookie_flags.png", "title": "Quan sát cookie và các thuộc tính", "url": "http://127.0.0.1:5006", "action": "Đăng nhập user demo rồi chọn cookie đang dùng.", "panel": "Application > Storage > Cookies", "must_show": "Name, Value đã che nếu cần, Domain, Path, HttpOnly, Secure, SameSite", "expected": "Các thuộc tính cookie local đọc được rõ ràng.", "caption": "Cookie demo và các thuộc tính bảo vệ được quan sát trong DevTools."},
    {"name": "02_plain_role_tamper.png", "title": "Plain Cookie trước và sau khi sửa role", "url": "http://127.0.0.1:5006/vulnerable/plain", "action": "Đăng nhập student, ghi trạng thái bị từ chối; sửa role=user thành role=admin và tải lại /admin.", "panel": "Application > Cookies + trang admin", "must_show": "giá trị trước/sau và quyền admin được cấp sai", "expected": "Server vulnerable tin role do client sửa.", "caption": "Sửa Plain Cookie làm vượt kiểm soát truy cập ở bản vulnerable."},
    {"name": "03_base64_role_tamper.png", "title": "Base64 Cookie decode và sửa role", "url": "http://127.0.0.1:5006/vulnerable/base64", "action": "Decode JSON bằng inspector tích hợp, đổi role thành admin, encode lại và tải trang admin.", "panel": "Base64 Inspector + Application > Cookies", "must_show": "JSON gốc, JSON đã sửa và kết quả server chấp nhận", "expected": "Base64 chỉ biểu diễn dữ liệu, không bảo vệ toàn vẹn.", "caption": "Cookie Base64 bị sửa role vì không có kiểm tra toàn vẹn."},
    {"name": "04_signed_valid.png", "title": "Signed Cookie hợp lệ", "url": "http://127.0.0.1:5006/secure/signed", "action": "Đăng nhập và truy cập profile/admin bằng cookie nguyên vẹn.", "panel": "Signature Inspector + Network", "must_show": "trạng thái chữ ký hợp lệ và request được xử lý", "expected": "Cookie chưa sửa được server xác minh.", "caption": "Signed Cookie nguyên vẹn vượt qua bước kiểm tra chữ ký."},
    {"name": "05_signed_tampered.png", "title": "Signed Cookie bị sửa bị từ chối", "url": "http://127.0.0.1:5006/secure/signed", "action": "Sửa đúng một ký tự trong cookie rồi tải lại.", "panel": "Application > Cookies + Signature Inspector", "must_show": "cookie đã sửa, chữ ký không hợp lệ và response từ chối", "expected": "Server không dùng dữ liệu đã bị sửa.", "caption": "Thay đổi một ký tự làm Signed Cookie bị server từ chối."},
    {"name": "06_encrypted_tampered.png", "title": "Authenticated encrypted cookie bị sửa", "url": "http://127.0.0.1:5006/secure/encrypted", "action": "Tạo token hợp lệ, sửa một ký tự rồi gửi lại.", "panel": "Encryption Inspector + Network", "must_show": "token hợp lệ, token bị sửa và kết quả kiểm tra toàn vẹn thất bại", "expected": "Server từ chối token bị can thiệp.", "caption": "Authenticated encryption phát hiện và từ chối token bị sửa."},
    {"name": "07_server_session_authz.png", "title": "Server-side Session và authorization", "url": "http://127.0.0.1:5006/secure/session", "action": "Đăng nhập student rồi admin; so sánh quyết định truy cập.", "panel": "Server Session + Authorization Inspector", "must_show": "cookie chỉ chứa session ID, role lấy từ database và quyết định quyền đúng", "expected": "Student bị từ chối; admin hợp lệ được phép.", "caption": "Server-side Session lấy quyền từ dữ liệu server cho từng request."},
    {"name": "08_session_lifecycle.png", "title": "Rotation, logout và token cũ", "url": "http://127.0.0.1:5006/secure/session", "action": "Ghi session trước/sau đăng nhập, logout rồi thử lại token cũ.", "panel": "Application > Cookies + Session/Audit Inspector", "must_show": "session ID rotate, logout invalidation và token cũ bị từ chối", "expected": "Phiên cũ không còn dùng được.", "caption": "Vòng đời phiên an toàn gồm rotation và hủy server-side khi logout."},
    {"name": "09_audit_test_report.png", "title": "Audit, kiểm thử và report artifacts", "url": "http://127.0.0.1:5006/audit-logs và Terminal Lab06", "action": "Ghép audit sự kiện tamper với kết quả pytest và danh sách report.", "panel": "Audit Inspector + Terminal", "must_show": "audit thật, tổng kết pytest thật và tên DOCX/PDF đã sinh", "expected": "Các artifact phản ánh đúng lệnh vừa chạy.", "caption": "Audit, kiểm thử và báo cáo của Lab06 được ghi nhận từ dữ liệu thật."},
)

EXPECTED_FILES = tuple(item["name"] for item in SCREENSHOTS)
