"""Canonical manual screenshot manifest; screenshots are captured by students."""


# --- Manual F12 evidence manifest (DOCX-only reporting) ---
LEGACY_SCREENSHOT_NAMES = ('01_home_overview.png',
 '02_database_seed.png',
 '03_vulnerable_login_normal.png',
 '04_vulnerable_login_request.png',
 '05_vulnerable_login_query.png',
 '06_quote_login_input.png',
 '07_quote_login_error.png',
 '08_auth_logic_input.png',
 '09_auth_query_changed.png',
 '10_auth_decision_vulnerable.png',
 '11_auth_session_created.png',
 '12_secure_login_same_input.png',
 '13_secure_login_parameter_binding.png',
 '14_secure_login_rejected.png',
 '15_secure_login_normal_success.png',
 '16_vulnerable_search_normal.png',
 '17_vulnerable_search_query.png',
 '18_quote_search_error.png',
 '19_expanded_search_input.png',
 '20_expanded_search_query.png',
 '21_expanded_search_results.png',
 '22_secure_search_same_input.png',
 '23_secure_search_binding.png',
 '24_secure_search_expected_results.png',
 '25_query_visualizer.png',
 '26_code_comparison_login.png',
 '27_code_comparison_search.png',
 '28_error_comparison.png',
 '29_password_hashing.png',
 '30_security_controls.png',
 '31_audit_logs.png',
 '32_trace_timeline.png',
 '33_presentation_mode.png',
 '34_pytest_passed.png',
 '35_coverage.png',
 '36_report_files.png')
F12_SCREENSHOTS = ({'filename': '37_login_normal_request.png',
  'objective': 'Chứng minh login bình thường',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/login',
  'account': 'admin_lab / AdminLab123!',
  'data': 'username=admin_lab; password che',
  'action': 'Submit',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /vulnerable/login',
  'field': 'Form Data',
  'required': 'Username nhìn thấy; password che trong ảnh',
  'expected': 'Login local hợp lệ',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request đăng nhập bình thường',
  'report_section': 'F12 / Login / Normal',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '38_login_normal_response.png',
  'objective': 'Ghi response login bình thường',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/login',
  'account': 'admin_lab',
  'data': 'Credential hợp lệ',
  'action': 'Chọn POST',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'POST /vulnerable/login',
  'field': 'Status/Response/Set-Cookie',
  'required': 'Redirect/success và session cookie che',
  'expected': 'Ứng dụng xác thực demo',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response đăng nhập bình thường',
  'report_section': 'F12 / Login / Response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '39_login_quote_request.png',
  'objective': 'Chứng minh input dấu nháy đơn',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/login',
  'account': 'Không cần tài khoản thật',
  'data': "username='; password giả lập",
  'action': 'Chọn scenario dấu nháy cố định và submit',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /vulnerable/login',
  'field': 'Form Data',
  'required': "Username chỉ là `'`; password che",
  'expected': 'Input tới vulnerable query',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request kiểm tra dấu nháy đơn',
  'report_section': 'F12 / Login / Quote',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '40_login_quote_response.png',
  'objective': 'Ghi lỗi an toàn/hành vi bất thường',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/login',
  'account': 'N/A',
  'data': "username='",
  'action': 'Chọn request',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'POST /vulnerable/login',
  'field': 'Status/Response',
  'required': 'Thông báo lỗi chung hoặc trace error category; không traceback/DB path',
  'expected': 'Lỗi được xử lý',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response của input dấu nháy',
  'report_section': 'F12 / Login / Quote response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '41_login_bypass_payload.png',
  'objective': 'Chứng minh authentication logic input cố định',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/login',
  'account': 'Payload local cố định',
  'data': "username=admin_lab' -- ; password bất kỳ giả lập",
  'action': 'Bấm scenario Authentication Logic',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload',
  'request': 'POST /vulnerable/login',
  'field': 'Form Data',
  'required': 'Username đúng chuỗi trong config; không payload khác',
  'expected': 'Comment làm thay đổi logic vulnerable',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Payload authentication bypass local',
  'report_section': 'F12 / Login / Vulnerable payload',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '42_login_bypass_response.png',
  'objective': 'Chứng minh vulnerable đăng nhập sai logic',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/login',
  'account': 'admin_lab qua demo local',
  'data': 'Payload cố định',
  'action': 'Chọn POST bypass',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'POST /vulnerable/login',
  'field': 'Response và status',
  'required': 'Response/UI cho thấy session tạo qua `vulnerable_local_demo`',
  'expected': 'Vulnerable chấp nhận không đúng logic password',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response vulnerable authentication bypass',
  'report_section': 'F12 / Login / Vulnerable response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '43_secure_login_same_payload.png',
  'objective': 'Chứng minh prepared statement giữ logic',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/secure/login',
  'account': 'Không đăng nhập',
  'data': "Cùng username admin_lab' -- ",
  'action': 'Submit secure',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Payload/Response',
  'request': 'POST /secure/login',
  'field': 'Form Data và Response',
  'required': 'Input được coi là username literal; response từ chối chung',
  'expected': 'Bản secure không bypass',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Secure login từ chối cùng payload',
  'report_section': 'F12 / Login / Secure',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '44_search_normal_request.png',
  'objective': 'Chứng minh query search bình thường',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/search?keyword=USB',
  'account': 'N/A',
  'data': 'keyword=USB',
  'action': 'Tìm kiếm',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /vulnerable/search?keyword=USB',
  'field': 'Query String Parameters',
  'required': 'keyword=USB',
  'expected': 'Kết quả chỉ tên chứa USB',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request search bình thường',
  'report_section': 'F12 / Search / Normal',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '45_search_normal_response.png',
  'objective': 'Ghi response search bình thường',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/search?keyword=USB',
  'account': 'N/A',
  'data': 'USB',
  'action': 'Chọn GET',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'GET /vulnerable/search?keyword=USB',
  'field': 'Response',
  'required': 'Danh sách dự kiến chứa USB; status 200',
  'expected': 'Baseline result set',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response search bình thường',
  'report_section': 'F12 / Search / Response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '46_search_expanded_request.png',
  'objective': 'Chứng minh điều kiện search bị thay đổi',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/search',
  'account': 'N/A',
  'data': "keyword=%' OR 1=1 -- ",
  'action': 'Dùng scenario Expanded local search',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /vulnerable/search?keyword=...',
  'field': 'Query String Parameters',
  'required': 'Keyword fixed được URL encode/decoded đúng',
  'expected': 'Request chỉ đọc database local',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request search thay đổi điều kiện',
  'report_section': 'F12 / Search / Tampered',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '47_search_expanded_response.png',
  'objective': 'Chứng minh result set ngoài dự kiến',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/vulnerable/search',
  'account': 'N/A',
  'data': 'Payload expanded cố định',
  'action': 'Chọn GET expanded',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'GET /vulnerable/search?keyword=...',
  'field': 'Response',
  'required': 'Nhiều sản phẩm ngoài từ khóa bình thường; không dữ liệu bảng khác',
  'expected': 'Vulnerable logic bị mở rộng',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response vulnerable trả dữ liệu ngoài dự kiến',
  'report_section': 'F12 / Search / Vulnerable response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '48_secure_search_request.png',
  'objective': 'Chứng minh secure bind cùng input',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/secure/search',
  'account': 'N/A',
  'data': "keyword=%' OR 1=1 -- ",
  'action': 'Submit secure search',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /secure/search?keyword=...',
  'field': 'Query String Parameters',
  'required': 'Cùng keyword tới route secure',
  'expected': 'Dữ liệu tách khỏi cấu trúc SQL',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request secure search cùng input',
  'report_section': 'F12 / Search / Secure request',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '49_secure_search_response.png',
  'objective': 'Chứng minh secure không đổi logic query',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/secure/search',
  'account': 'N/A',
  'data': 'Payload expanded cố định',
  'action': 'Chọn request secure',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Response/Preview',
  'request': 'GET /secure/search?keyword=...',
  'field': 'Response',
  'required': 'Không mở rộng toàn bộ product; prepared=true/placeholder nếu UI trace hiện',
  'expected': 'Prepared statement hiệu quả',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure không mở rộng kết quả',
  'report_section': 'F12 / Search / Secure response',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '50_login_cookie_masked.png',
  'objective': 'Chứng minh session sau login nhưng không lộ token',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5005/dashboard',
  'account': 'admin_lab',
  'data': 'Login hợp lệ',
  'action': 'Reload dashboard',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application Cookies; Network Headers',
  'request': 'GET /dashboard',
  'field': 'Cookie name/flags và Request Header',
  'required': '`lab05_session` hiện diện; Value che; HttpOnly/SameSite phản ánh config',
  'expected': 'Session được tạo mà không lộ secret',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Cookie phiên Lab05 đã che',
  'report_section': 'F12 / Session',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False})
OPTIONAL_SCREENSHOT_NAMES = frozenset(name for name in LEGACY_SCREENSHOT_NAMES if 'pytest' in name or 'coverage' in name)
ALL_SCREENSHOTS = tuple({'filename': name, 'optional': name in OPTIONAL_SCREENSHOT_NAMES} for name in LEGACY_SCREENSHOT_NAMES) + F12_SCREENSHOTS
