"""Canonical manual screenshot manifest; screenshots are captured by students."""


# --- Manual F12 evidence manifest (DOCX-only reporting) ---
LEGACY_SCREENSHOT_NAMES = ('01_home_overview.png',
 '02_login_accounts.png',
 '03_plain_student_login.png',
 '04_plain_cookie_devtools.png',
 '05_plain_cookie_attributes.png',
 '06_plain_admin_denied.png',
 '07_plain_role_before.png',
 '08_plain_role_modified_devtools.png',
 '09_plain_admin_allowed.png',
 '10_plain_authorization_inspector.png',
 '11_plain_timeline.png',
 '12_plain_final_verdict.png',
 '13_base64_login.png',
 '14_base64_cookie_devtools.png',
 '15_base64_original_value.png',
 '16_base64_decoded_json.png',
 '17_base64_modified_json.png',
 '18_base64_reencoded_value.png',
 '19_base64_admin_allowed.png',
 '20_base64_inspector.png',
 '21_base64_final_verdict.png',
 '22_signed_cookie_login.png',
 '23_signed_cookie_attributes.png',
 '24_signed_cookie_valid.png',
 '25_signature_inspector_valid.png',
 '26_signed_cookie_modified_devtools.png',
 '27_signed_cookie_rejected.png',
 '28_signature_inspector_invalid.png',
 '29_encrypted_cookie_demo.png',
 '30_encoding_signing_encryption.png',
 '31_server_session_student_login.png',
 '32_server_session_cookie.png',
 '33_server_session_inspector.png',
 '34_student_admin_denied.png',
 '35_admin_server_session_login.png',
 '36_admin_access_allowed.png',
 '37_database_role_lookup.png',
 '38_session_rotation.png',
 '39_logout_invalidation.png',
 '40_old_session_rejected.png',
 '41_code_comparison.png',
 '42_security_controls.png',
 '43_audit_logs.png',
 '44_trace_timeline.png',
 '45_presentation_mode.png',
 '46_pytest_passed.png',
 '47_coverage.png',
 '48_report_files.png')
F12_SCREENSHOTS = ({'filename': '49_cookie_initial_application.png',
  'objective': 'Ghi cookie ban đầu và đầy đủ flags',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/vulnerable/plain/profile',
  'account': 'student / Student123!',
  'data': 'Plain Cookie Demo',
  'action': 'Đăng nhập rồi mở Cookies',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application/Storage > Cookies',
  'request': 'GET /vulnerable/plain/profile',
  'field': 'Name, Value, Domain, Path, HttpOnly, Secure, SameSite',
  'required': 'lab06_username=student; lab06_role=user; flags đúng config; chỉ cookie Lab06',
  'expected': 'Baseline trước poisoning',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Cookie Plain ban đầu trong Application',
  'report_section': 'F12 / Plain / Before',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '50_plain_cookie_request_header.png',
  'objective': 'Chứng minh cookie được gửi trong HTTP request',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/vulnerable/plain/admin',
  'account': 'student',
  'data': 'role=user',
  'action': 'Mở admin trước khi sửa',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'GET /vulnerable/plain/admin',
  'field': 'Request Headers > Cookie',
  'required': 'Tên cookie/role hiện diện; giá trị nhạy cảm khác che',
  'expected': 'Request bị từ chối khi role=user',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Cookie header trước poisoning',
  'report_section': 'F12 / Plain / Request before',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '51_plain_cookie_modified_application.png',
  'objective': 'Chứng minh role được sửa thủ công',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/vulnerable/plain/admin',
  'account': 'student',
  'data': 'lab06_role: user → admin',
  'action': 'Sửa Value trong Application và Enter',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application/Storage > Cookies',
  'request': 'N/A',
  'field': 'Cookie row',
  'required': 'Đúng origin, Name lab06_role, Value admin, flags không đổi',
  'expected': 'Browser lưu giá trị tampered',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Sửa role cookie bằng DevTools',
  'report_section': 'F12 / Plain / Modified',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '52_plain_admin_request_response.png',
  'objective': 'Chứng minh vulnerable cho phép sau sửa',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/vulnerable/plain/admin',
  'account': 'student',
  'data': 'lab06_role=admin',
  'action': 'Reload admin',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'GET /vulnerable/plain/admin',
  'field': 'Cookie Request Header và Response',
  'required': 'Request gửi role=admin; response 200/admin allowed/verdict vulnerable',
  'expected': 'Server tin cookie client',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response vulnerable cho phép admin',
  'report_section': 'F12 / Plain / Vulnerable',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '53_base64_cookie_modified_request.png',
  'objective': 'Chứng minh Base64 cookie bị sửa',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/vulnerable/base64/admin',
  'account': 'student',
  'data': 'lab06_profile_b64 dùng giá trị role=admin read-only của UI',
  'action': 'Sửa cookie thủ công rồi reload',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application Cookies; Network Headers',
  'request': 'GET /vulnerable/base64/admin',
  'field': 'Cookie và Response',
  'required': 'Tên cookie; giá trị rút gọn/che; response cho phép; không dùng decoder ngoài',
  'expected': 'Base64 không cung cấp integrity',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request Base64 sau sửa role',
  'report_section': 'F12 / Base64 / Vulnerable',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '54_signed_cookie_valid_request.png',
  'objective': 'Chứng minh signed cookie hợp lệ',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/secure/signed/profile',
  'account': 'student',
  'data': 'Signed Cookie Demo',
  'action': 'Login và mở profile',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'GET /secure/signed/profile',
  'field': 'Cookie header và Response',
  'required': 'Cookie rút gọn/che, response valid, Signature Inspector hợp lệ',
  'expected': 'Signed cookie chấp nhận khi nguyên vẹn',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Request signed cookie hợp lệ',
  'report_section': 'F12 / Signed / Valid',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '55_signed_cookie_tampered_application.png',
  'objective': 'Chứng minh sửa đúng một ký tự',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/secure/signed/profile',
  'account': 'student',
  'data': 'Sửa một ký tự lab06_signed_profile',
  'action': 'Edit Value và Enter',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application/Storage > Cookies',
  'request': 'N/A',
  'field': 'Cookie row',
  'required': 'Origin local, tên cookie, giá trị đã che nhưng thể hiện đã sửa',
  'expected': 'Browser lưu token tampered',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Sửa signed cookie bằng DevTools',
  'report_section': 'F12 / Signed / Tamper',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '56_signed_cookie_rejected_response.png',
  'objective': 'Chứng minh chữ ký sai bị từ chối',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/secure/signed/profile',
  'account': 'student',
  'data': 'Signed cookie đã sửa',
  'action': 'Reload',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'GET /secure/signed/profile',
  'field': 'Cookie header, status, Response',
  'required': 'Response từ chối/invalid signature; không dùng payload cho authorization',
  'expected': 'Integrity check hiệu quả',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure từ chối signed cookie sửa',
  'report_section': 'F12 / Signed / Rejected',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '57_server_session_cookie_request.png',
  'objective': 'Chứng minh cookie session không chứa role',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/secure/session/profile',
  'account': 'student',
  'data': 'Server-side Session Demo',
  'action': 'Login và mở profile',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Application Cookies; Network Headers',
  'request': 'GET /secure/session/profile',
  'field': 'lab06_session và Request Header',
  'required': 'Cookie value che/fingerprint; không user_id/role trong cookie',
  'expected': 'Role được tra phía server',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Server-side session cookie đã che',
  'report_section': 'F12 / Session / Cookie',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '58_student_admin_denied_response.png',
  'objective': 'Chứng minh database role user bị từ chối',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/secure/session/admin',
  'account': 'student',
  'data': 'Session student hợp lệ',
  'action': 'Mở admin',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'GET /secure/session/admin',
  'field': 'Status/Response',
  'required': '403/denied; Authorization Inspector role source database',
  'expected': 'Secure authorization từ chối student',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure từ chối student',
  'report_section': 'F12 / Session / Denied',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '59_admin_session_allowed_response.png',
  'objective': 'Chứng minh admin thật được phép',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/secure/session/admin',
  'account': 'admin_lab / AdminLab123!',
  'data': 'Server-side Session Demo',
  'action': 'Logout/reset; login admin; mở admin',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers/Response',
  'request': 'GET /secure/session/admin',
  'field': 'Status/Response',
  'required': '200/allowed; role admin từ database; cookie value che',
  'expected': 'Admin hợp lệ được phép',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Response secure cho phép admin thật',
  'report_section': 'F12 / Session / Allowed',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False},
 {'filename': '60_secure_set_cookie_headers.png',
  'objective': 'Chứng minh Set-Cookie secure modes',
  'setup': 'Server local đang chạy; xóa request cũ trong Network.',
  'url': 'http://127.0.0.1:5006/login',
  'account': 'student',
  'data': 'Signed hoặc Server-side Session Demo',
  'action': 'Login và chọn POST',
  'ui_tab': 'Trang chức năng tương ứng.',
  'f12_tab': 'Network > Headers',
  'request': 'POST /login',
  'field': 'Response Headers > Set-Cookie',
  'required': 'Tên cookie tương ứng, HttpOnly, SameSite=Lax, Path=/, Secure theo config local; giá trị che',
  'expected': 'Flags khớp `cookie_options`',
  'troubleshooting': 'Bật Preserve log, bỏ bộ lọc sai, thực hiện lại thao tác rồi chọn đúng request.',
  'scope': 'Giữ thanh địa chỉ, UI kết quả và vùng DevTools liên quan trong cùng ảnh.',
  'caption': 'Set-Cookie của chế độ secure',
  'report_section': 'F12 / Secure / Set-Cookie',
  'analysis': 'Bằng chứng này nối dữ liệu client với request/response quan sát được. Đối chiếu vulnerable và secure để thấy '
              'nguyên nhân kỹ thuật và hiệu quả bản vá.',
  'optional': False})
OPTIONAL_SCREENSHOT_NAMES = frozenset(name for name in LEGACY_SCREENSHOT_NAMES if 'pytest' in name or 'coverage' in name)
ALL_SCREENSHOTS = tuple({'filename': name, 'optional': name in OPTIONAL_SCREENSHOT_NAMES} for name in LEGACY_SCREENSHOT_NAMES) + F12_SCREENSHOTS
